### ISSUE TITLE
Hashing with salt

### ISSUE THREAD

**Issue by kamatama41** [kamatama41/embulk-filter-hash#18]
ref: https://blog.liclab.com/2017-08-19/extract-and-anonymyze-by-embulk/

> ハッシュ化する際にsaltつけたい

**Comment by kamatama41** [comment]
### How should it be implemented? 🤔 
1. Specify a fixed salt via `salt` property 
```yaml
filters:
  - type: hash
    columns:
    - { name: email, salt: fooooooooo }
```

2. Specify a column to be used as salt via `salt_column` property
```yaml
filters:
  - type: hash
    columns:
    - { name: email, salt_column: user_id }
```
